name: rin_wallet
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  flutter_json_view: ^1.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  local_auth: ^2.1.7
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  uuid: ^4.0.0
  file_picker: ^5.5.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  collection: ^1.18.0
  image: ^4.1.3
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
